classic: false

# == Blocks ==
# This specifies the columns and their order
# when using the long and the tree layout.
# Possible values:
#   permission, user, group, context, size,
#   date, name, inode, links, git

blocks:
  - permission
  - user
  - group
  - size
  - date
  - name
  - git

date: relative

color:
  when: auto
  theme: custom

# == Icons ==
icons:
  # When to use icons.
  # When "classic" is set, this is set to "never".
  # Possible values: always, auto, never
  when: auto
  theme: fancy

indicators: true
size: short
